# Arrange displays in a ROW (default, left to right) or a COLUMN (top to bottom)
ARRANGE: ROW

# Align ROWs at the TOP (default), MIDDLE or BOTTOM
# Align COLUMNs at the LEFT (default), MIDDLE or RIGHT
ALIGN: TOP


# The default ORDER is simply the order in which the displays are discovered.
# Define your own.
ORDER:
  - 'Lenovo Group Limited LEN S28u-10 VNA61CZ9'
  - 'Lenovo Group Limited LEN S28u-10 VNA61CZ5'
  - 'Lenovo Group Limited T27hv-20 V306MXG0'
  - 'eDP-1'


# The default is to scale each display by DPI.
# This may be disabled and scale 1 will be used, unless a SCALE has been specified.
AUTO_SCALE: FALSE


# Auto scale may be overridden for each display.
SCALE:
  - NAME_DESC: 'eDP-1'
    SCALE: 2

  - NAME_DESC: 'Lenovo Group Limited LEN S28u-10 VNA61CZ9'
    SCALE: 1.15

  - NAME_DESC: 'Lenovo Group Limited LEN S28u-10 VNA61CZ5'
    SCALE: 1.15


# Laptop displays usually start with eDP e.g. eDP-1. This may be overridden if
# your laptop is different.
#LAPTOP_DISPLAY_PREFIX: 'eDP'


# Use the maximum refresh rate for resolution of the preferred mode.
# Warning: this may result in an unusable display.
MAX_PREFERRED_REFRESH:
  #- 'monitor description'
  #- 'HDMI-1'


# One of: ERROR, WARNING, INFO (default), DEBUG
LOG_THRESHOLD: INFO


# Disable the specified displays.
# To disable/enable on-the-fly see recipe: https://github.com/alex-courtis/way-displays#on-the-fly-recipes
DISABLED:
  #- "eDP-1"

