#
# ~/.bashrc
#

[[ $- != *i* ]] && return

colorize(){
    echo "\[\e[$1\]$2\[\e[0m\]"
}

[ -r /usr/share/bash-completion/bash_completion ] && . /usr/share/bash-completion/bash_completion

[[ -z "$FUNCNEST" ]] && export FUNCNEST=100
bind '"\e[A":history-search-backward'
bind '"\e[B":history-search-forward'

alias ls='ls --color=auto'
alias grep='grep --colour=auto'
alias egrep='egrep --colour=auto'
alias fgrep='fgrep --colour=auto'

alias cp="cp -i"                          # confirm before overwriting something
alias df='df -h'                          # human-readable sizes
alias free='free -m'                      # show sizes in MB
alias more=less

xhost +local:root > /dev/null 2>&1

# Bash won't get SIGWINCH if another process is in the foreground.
# Enable checkwinsize so that bash will check the terminal size when
# it regains control.  #65623
# http://cnswww.cns.cwru.edu/~chet/bash/FAQ (E11)
shopt -s checkwinsize

shopt -s expand_aliases

# Enable history appending instead of overwriting.  #139609
shopt -s histappend

export EDITOR=/usr/bin/vim
export VISUAL=$EDITOR
export BROWSER=/usr/bin/google-chrome-stable
# export BROWSER=/usr/bin/firefox-beta

if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

show_virtual_env() {
  if [ -n "$VIRTUAL_ENV" ]; then
    echo "($(basename $VIRTUAL_ENV))"
  fi
}

USER_P=$(colorize "0;33m" "\u")
DIR_P=$(colorize "0;32m" "\w")
GIT_P='$(__git_ps1)'
PC_P=$(colorize "0;33m" "\$")

PS1="$USER_P->$DIR_P$GIT_P$PC_P "

PS1='$(show_virtual_env)'$PS1


. ~/sources/git-completion.bash
. ~/sources/git-prompt.sh

. /etc/profile.d/autojump.bash
alias t=j

load-ssh-agent(){
    if [[ "$SSH_AGENT_PID" == "" ]]; then
        eval "$(<~/.ssh-agent-thing)" > /dev/null 2>&1
    fi
}


if ! pgrep -u "$USER" ssh-agent > /dev/null; then
    ssh-agent > ~/.ssh-agent-thing
    load-ssh-agent
    ssh-add /home/sindri/.ssh/id_rsa
else
    load-ssh-agent
fi


eval "$(pyenv init --path)"

export PATH="/home/sindri/bin:$PATH"

eval "$(direnv hook bash)"
eval "$(pyenv init -)"
eval "$(gh completion -s bash)"

eval "$(pyenv virtualenv-init -)"

eval "$(register-python-argcomplete pipx)"
complete -C /var/lib/tfenv/versions/1.0.0/terraform terraform
complete -C '/usr/bin/aws_completer' aws

export NVM_DIR="/home/sindri/.nvm"
. /usr/share/nvm/nvm.sh
. /usr/share/nvm/bash_completion

export GOPATH=/home/sindri/go
export PATH="/home/sindri/.local/bin/:$PATH"
