#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

# xrandr --newmode "2048x1152"  197.00  2048 2184 2400 2752  1152 1155 1160 1195 -hsync +vsync
# xrandr --addmode eDP-1 2048x1152

systemctl --user import-environment DISPLAY

exec i3
