k9s:
  refreshRate: 2
  maxConnRetry: 5
  enableMouse: false
  headless: false
  logoless: false
  crumbsless: false
  readOnly: false
  noIcons: false
  logger:
    tail: 500
    buffer: 5000
    sinceSeconds: -1
    fullScreenLogs: false
    textWrap: false
    showTime: false
  currentContext: island-ids-prod
  currentCluster: arn:aws:eks:eu-west-1:567113216315:cluster/ids-prod-cluster01
  clusters:
    arn:aws:eks:eu-west-1:013313053092:cluster/dev-cluster01:
      namespace:
        active: identity-server
        favorites:
        - judicial-system
        - air-discount-scheme
        - identity-server
        - application-system
        - islandis
        - linkerd
        - socat
        - spinnaker
        - actions-runner-system
      view:
        active: pod
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
    arn:aws:eks:eu-west-1:251502586493:cluster/prod-cluster01:
      namespace:
        active: ""
        favorites:
        - vidspyrna
        - all
        - kube-system
        - application-system
        - islandis
        - endorsement-system
        - socat
        - judicial-system
        - operations
      view:
        active: ing
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
    arn:aws:eks:eu-west-1:261174024191:cluster/staging-cluster01:
      namespace:
        active: identity-server
        favorites:
        - identity-server
        - calico-system
        - kube-system
        - default
      view:
        active: pod
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
    arn:aws:eks:eu-west-1:567113216315:cluster/ids-prod-cluster01:
      namespace:
        active: identity-server
        favorites:
        - kube-system
        - socat
        - identity-server
        - all
        - default
      view:
        active: pod
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
    arn:aws:eks:eu-west-1:821090935708:cluster/shared-cluster01:
      namespace:
        active: kube-system
        favorites:
        - kube-system
        - e2e-staging
        - e2e-dev
        - feature-deployments
        - all
        - default
      view:
        active: pod
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
